# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "ffmpeg" ]
  pull_request:
    branches: [ "ffmpeg" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019
    steps:
      - name: build
        shell: cmd
        run: |
          vcpkg.exe install ffmpeg[all-nonfree]:x64-windows-static
          vcpkg export ffmpeg[all-nonfree]:x64-windows-static --7zip --output-dir=./
      - uses: actions/upload-artifact@v3
        with:
          name: Release
          path: ./vcpkg-export-*.7z
