# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "ffmpeg-rdp" ]
  pull_request:
    branches: [ "ffmpeg-rdp" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: set_env
        shell: cmd
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq upgrade
          sudo apt-get -qq install ragel cvs yasm pax nasm gperf autogen autoconf-archive
          sudo -H pip3 -qq install meson ninja
          cd ~
          git clone --depth=1 https://github.com/rdp/ffmpeg-windows-build-helpers.git f
          cd f
          git clone --depth=1 https://github.com/FFmpeg/FFmpeg.git ffmpeg
      - name: build
        shell: cmd
        run: |
          cd ~/f
          ./cross_compile_ffmpeg.sh --ffmpeg-source-dir=~/f/ffmpeg --disable-nonfree=n --sandbox-ok=y --compiler-flavors=win64 --build_x264_with_libav=y --build-ffmpeg-shared=y --build-libmxf=y --build-mp4box=y --build-mplayer=y --build-lsw=y --build-ismindex=y --build-svt=y --build-dvbtee=y
      - uses: actions/upload-artifact@v3
        with:
          name: nonfree
          path: |
            ~/f/ffmpeg/*.exe
            ~/f/ffmpeg/*.dll
