name: CI
on:
  push:
    branches: [ "helpers" ]
  # pull_request:
  #   branches: [ "ffmpeg-rdp" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set_env
        run: |
          sudo apt-get install subversion ragel curl texinfo g++ ed bison flex cvs yasm automake libtool autoconf gcc cmake git make pkg-config zlib1g-dev unzip pax nasm gperf autogen bzip2 autoconf-archive p7zip-full meson clang python3-distutils -y
          cd C:\
          git clone --depth=1 https://github.com/rdp/ffmpeg-windows-build-helpers.git f
      - name: build
        run: |
          cd C:\f
          ./cross_compile_ffmpeg.sh --build-ffmpeg-shared=y --disable-nonfree=n --compiler-flavors=win64
          ls
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: nonfree
      #     path: |
      #       ~/f/ffmpeg/*.exe
      #       ~/f/ffmpeg/*.dll
